const data = {
    products: [{
            _id: '1',
            name: 'Slim Shirt',
            category: 'Shirt',
            Image: '/img/p1.png',
            price: 135,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Full Sleevs Shirt',
            category: 'Shirt',
            Image: '/img/p2.png',
            price: 140,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Roadster T-Shirt',
            category: 'Shirt',
            Image: '/img/p3.png',
            price: 103,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Rebel logo T-Shirt',
            category: 'Shirt',
            Image: '/img/p4.png',
            price: 130,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Darkest T-Shirt',
            category: 'Shirt',
            Image: '/img/p5.png',
            price: 135,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Yellow Darkest Slim Shirt',
            category: 'Shirt',
            Image: '/img/p6.png',
            price: 105,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Light Slim Shirt',
            category: 'Shirt',
            Image: '/img/p7.png',
            price: 100,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Logo T-Shirt',
            category: 'Shirt',
            Image: '/img/p8.png',
            price: 130,
            brand: 'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;